services:
  # A Docker web service
  - type: web
    name: reverse
    env: docker
    repo: https://github.com/mahdi-saberi/nginx-reverse-proxy
    envVars:
    - key: UPSTREAM_HTTP_ADDRESS
      value: https://i.instagram.com/
    - key: PORT
      value: 80
